# Generated by Django 4.1.3 on 2023-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_shipped_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='shipped_id',
            field=models.CharField(blank=True, default='PJB-00<function create_new_ref_number at 0x0000025929F46B60>', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('shipped', 'shipped'), ('delivered', 'delivered'), ('pending', 'pending')], default='pending', max_length=255),
        ),
    ]
