# Generated by Django 4.1.3 on 2023-04-06 14:00

from django.db import migrations, models
import packages.utils


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_package_shipped_id_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='shipped_id',
            field=models.CharField(blank=True, default=packages.utils.create_new_ref_number, editable=False, max_length=255, unique=True),
        ),
    ]
